name: least-error
author: Galen Huntington

defaults: galenhuntington/hpack-defaults@27874600a9673795a129b2f7523451793a39aaf4

ghc-options: -O2 -rtsopts

source-dirs:
   - .

executables:
   demo:
      main: demo.hs

dependencies:
   - base
   - base-prelude
   - vector
   - deepseq
   - mono-traversable

