name: least-error
author: Galen Huntington

defaults: galenhuntington/hpack-defaults@f14c1cdf9475cb4f76db482074cea745a9f5f695

ghc-options: -O2 -rtsopts

source-dirs:
   - .

executables:
   demo:
      main: demo.hs

dependencies:
   - base
   - base-prelude
   - vector
   - deepseq
   - mono-traversable

